### Pessoa

POST http://localhost:5000/api/aluno HTTP/1.1
Content-Type: application/json

{
    "id_pessoa": 249,
    "destro_canhoto": "d",
    "id_responsavel": null,
    "dt_inicio": "2000-04-12"
}

###

POST http://localhost:5000/api/pessoa/
Content-Type: application/json

{
    "nome_pessoa":"Tomás Fiori Bolsoni",
    "dt_nasc_pessoa":"2004-03-04",
    "cpf_pessoa":"124141315",
    "rg_pessoa":"431554135",
    "email_pessoa":"admf",
    "senha_pessoa":"1",
    "telefone_pessoa":"149999991",
    "genero":"m",
    "id_endereco":3,
    "adm":1
}

### Endereco

POST http://localhost:5000/api/endereco HTTP/1.1
Content-Type: application/json

{
    "cep":"16401-140",
    "estado":"SP",
    "cidade":"Lins",
    "bairro":"Jardim Linense", 
    "rua":"Nome muito Grande", 
    "numero":"335"
}

###

GET http://localhost:5000/api/aluno/allData/2
Content-Type: application/json
