### Pessoa

POST http://localhost:5000/api/pessoa HTTP/1.1
Content-Type: application/json

{
    "nome_pessoa":"ADM",
    "dt_nasc_pessoa":"1998-05-10",
    "cpf_pessoa":"12413245",
    "rg_pessoa":"4332153341",
    "email_pessoa":"admin",
    "senha_pessoa":"admin123",
    "telefone_pessoa":"14 9999999",
    "id_endereco":1
}

###

GET  http://localhost:5000/api/pessoa

###

PUT http://localhost:3000/api/pessoa/1
Content-Type: application/json

{
    "nome_pessoa":"Francisco",
    "dt_nasc_pessoa":"2004-03-04",
    "cpf_pessoa":"1241413513",
    "rg_pessoa":"431511341",
    "email_pessoa":"eduardo@teste.com.br",
    "senha_pessoa":"eduardo123",
    "telefone_pessoa":"14 9999999",
    "id_endereco":1
}

###

DELETE http://localhost:3000/api/pessoa/1

### Endereco

POST http://localhost:3000/api/endereco HTTP/1.1
Content-Type: application/json

{
    "cep":"16401-093",
    "estado":"São-Paulo",
    "cidade":"Lins",
    "bairro":"Jardim Tropical", 
    "rua":"São Cristovão", 
    "numero":"261"
}

###

GET  http://localhost:3000/api/endereco

###

PUT http://localhost:3000/api/endereco/1
Content-Type: application/json

{
    "cep":"16401-093",
    "estado":"São-Paulo",
    "cidade":"Lins",
    "bairro":"Jardim Tropical", 
    "rua":"São Cristovão", 
    "numero":"261"
}

###

DELETE http://localhost:3000/api/endereco/1

###

POST http://localhost:5000/login


